name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Test application
        run: npm test

      - name: Build application
        run: npm run build

      - name: Create .env file
        run: touch .env

      - name: Setup Stripe secrets
        run: |
          echo STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }} >> .env 
          echo STRIPE_PAYMENT_SUCCESS_WEBHOOK_SECRET_KEY=${{ secrets.STRIPE_PAYMENT_SUCCESS_WEBHOOK_SECRET_KEY }} >> .env
      
      - name: Setup Nylas secrets
        run: |
          echo NYLAS_CLIENT_ID=${{ secrets.NYLAS_CLIENT_ID }} >> .env 
          echo NYLAS_CLIENT_SECRET=${{ secrets.NYLAS_CLIENT_SECRET }} >> .env
          echo NYLAS_MAIN_ACCOUNT_ACCESS_TOKEN=${{ secrets.NYLAS_MAIN_ACCOUNT_ACCESS_TOKEN }} >> .env
      
      - name: Restart server application
        run: pm2 restart aprendecodigoapi
