name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Test application
        run: npm test

      - name: Build application
        run: npm run build

      - name: Create .env file
        run: touch .env

      - name: Setup STRIPE_SECRET_KEY
        run: echo ${{ secrets.STRIPE_SECRET_KEY }} >> .env

      - name: Restart server application
        run: pm2 restart aprendecodigoapi
